GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/63f74c731bd02e8465c4b8d4

###

POST http://localhost:3000/subscribers/
Content-Type: application/json

{
    "name": "Testi Kayttaja",
    "subscribedToChannel": "Test Channel"
}

###

DELETE http://localhost:3000/subscribers/63f74c731bd02e8465c4b8d4

###

PATCH http://localhost:3000/subscribers/63f753a4d002452a5be989a
Content-Type: application/json

{
    "name": "New Name"
}